-- Generated from catalog/products.json — do not edit by hand.
-- Regenerate with: python catalog/gen-seed.py
-- BOOTSTRAP ONLY: inserts new rows, DOES NOTHING on conflict. The DB is
-- the source of truth; this must never overwrite live admin-owned data.

insert into public.products
  (sku, name, price, collection, tier, label, max_quantity, item_url,
   cart_image, images, available, ai_note, position, published)
values
  ('BP-N-004', 'Blue Lapis, Sodalite & Quartz Necklace', 150.00, 'stone-earth', 'signature', 'Signature Piece', 1, '/shop.html', 'images/featured/bp-n-004-detail.jpg', '[{"url": "images/featured/bp-n-004-worn.jpg", "alt": "Blue Lapis, Sodalite & Quartz Necklace — worn"}, {"url": "images/featured/bp-n-004-detail.jpg", "alt": "Blue Lapis, Sodalite & Quartz Necklace — detail"}]'::jsonb, true, true, 10, true),
  ('BP-N-030', 'Blue Glass & Starfish Necklace', 55.00, 'sea-shore', 'signature', 'Signature Series', 1, '/shop.html', 'images/featured/bp-n-030-detail.jpg', '[{"url": "images/featured/bp-n-030-worn.jpg", "alt": "Blue Glass & Starfish Necklace — worn"}, {"url": "images/featured/bp-n-030-detail.jpg", "alt": "Blue Glass & Starfish Necklace — detail"}]'::jsonb, true, true, 20, true),
  ('BP-E-011', 'Emerald Crystal & Glass Pearl Earrings', 38.00, 'pearl-crystal', 'signature', 'Signature Series', 1, '/shop.html', 'images/featured/bp-e-011-detail.jpg', '[{"url": "images/featured/bp-e-011-worn.jpg", "alt": "Emerald Crystal & Glass Pearl Earrings — worn"}, {"url": "images/featured/bp-e-011-detail.jpg", "alt": "Emerald Crystal & Glass Pearl Earrings — detail"}]'::jsonb, true, true, 30, true),
  ('BP-N-010', 'Shells, Howlite & Tiger''s Eye Necklace', 65.00, 'sea-shore', 'signature', 'Signature Series', 1, '/shop.html', 'images/featured/bp-n-010-detail.jpg', '[{"url": "images/featured/bp-n-010-worn.jpg", "alt": "Shells, Howlite & Tiger''s Eye Necklace — worn"}, {"url": "images/featured/bp-n-010-detail.jpg", "alt": "Shells, Howlite & Tiger''s Eye Necklace — detail"}]'::jsonb, true, true, 40, true),
  ('BP-N-042', 'Onyx, Druzy, Gold & Pearl Necklace', 70.00, 'stone-earth', 'signature', 'Signature Series', 1, '/shop.html', 'images/featured/bp-n-042-detail.jpg', '[{"url": "images/featured/bp-n-042-worn.jpg", "alt": "Onyx, Druzy, Gold & Pearl Necklace — worn"}, {"url": "images/featured/bp-n-042-detail.jpg", "alt": "Onyx, Druzy, Gold & Pearl Necklace — detail"}]'::jsonb, true, true, 50, true),
  ('BP-B-003', 'Cream Pearl & Shell Coil Bracelet', 42.00, 'sea-shore', 'signature', 'Signature Series', 1, '/shop.html', 'images/featured/bp-b-003-detail.jpg', '[{"url": "images/featured/bp-b-003-worn.jpg", "alt": "Cream Pearl & Shell Coil Bracelet — worn"}, {"url": "images/featured/bp-b-003-detail.jpg", "alt": "Cream Pearl & Shell Coil Bracelet — detail"}]'::jsonb, true, true, 60, true),
  ('BP-N-043', 'Woven Aqua Rope Necklace', 70.00, 'hand-woven', 'signature', 'Signature Series · Bead-woven', 1, '/shop.html', 'images/featured/bp-n-043-detail.jpg', '[{"url": "images/featured/bp-n-043-worn.jpg", "alt": "Woven Aqua Rope Necklace — worn"}, {"url": "images/featured/bp-n-043-detail.jpg", "alt": "Woven Aqua Rope Necklace — detail"}]'::jsonb, true, true, 70, true),
  ('BP-E-023', 'Woven Amethyst Stud Earrings', 35.00, 'hand-woven', 'signature', 'Signature Series · Bead-woven', 1, '/shop.html', 'images/featured/bp-e-023-detail.jpg', '[{"url": "images/featured/bp-e-023-worn.jpg", "alt": "Woven Amethyst Stud Earrings — worn"}, {"url": "images/featured/bp-e-023-detail.jpg", "alt": "Woven Amethyst Stud Earrings — detail"}]'::jsonb, true, true, 80, true),
  ('BP-N-024', 'Blue Crystal & Porcelain Necklace', 65.00, 'pearl-crystal', 'signature', 'Signature Series', 1, '/shop.html', 'images/featured/bp-n-024-detail.jpg', '[{"url": "images/featured/bp-n-024-worn.jpg", "alt": "Blue Crystal & Porcelain Necklace — worn"}, {"url": "images/featured/bp-n-024-detail.jpg", "alt": "Blue Crystal & Porcelain Necklace — detail"}]'::jsonb, true, true, 90, true),
  ('BP-N-044', 'Rose Quartz, Grey Agate & Moonstone Necklace', 60.00, 'stone-earth', 'signature', 'Signature Series', 1, '/shop.html', 'images/featured/bp-n-044-detail.jpg', '[{"url": "images/featured/bp-n-044-worn.jpg", "alt": "Rose Quartz, Grey Agate & Moonstone Necklace — worn"}, {"url": "images/featured/bp-n-044-detail.jpg", "alt": "Rose Quartz, Grey Agate & Moonstone Necklace — detail"}]'::jsonb, true, true, 100, true),
  ('BP-E-042', 'Woven Pearl & Navy Cluster Earrings', 38.00, 'hand-woven', 'signature', 'Signature Series · Bead-woven', 1, '/shop.html', 'images/featured/bp-e-042-detail.jpg', '[{"url": "images/featured/bp-e-042-worn.jpg", "alt": "Woven Pearl & Navy Cluster Earrings — worn"}, {"url": "images/featured/bp-e-042-detail.jpg", "alt": "Woven Pearl & Navy Cluster Earrings — detail"}]'::jsonb, true, true, 110, true),
  ('BP-N-012', 'Pale Blue Crystal Cube Necklace', 55.00, 'pearl-crystal', 'signature', 'Signature Series', 1, '/shop.html', 'images/featured/bp-n-012-detail.jpg', '[{"url": "images/featured/bp-n-012-worn.jpg", "alt": "Pale Blue Crystal Cube Necklace — worn"}, {"url": "images/featured/bp-n-012-detail.jpg", "alt": "Pale Blue Crystal Cube Necklace — detail"}]'::jsonb, true, true, 120, true),
  ('BP-B-006', 'Shell, Howlite & Pearl Bracelet', 42.00, 'sea-shore', 'signature', 'Signature Series', 1, '/shop.html', 'images/featured/bp-b-006-detail.jpg', '[{"url": "images/featured/bp-b-006-worn.jpg", "alt": "Shell, Howlite & Pearl Bracelet — worn"}, {"url": "images/featured/bp-b-006-detail.jpg", "alt": "Shell, Howlite & Pearl Bracelet — detail"}]'::jsonb, true, true, 130, true),
  ('BP-STUDIO-001', 'Silver Plumeria Drop Earrings', 85.00, 'sea-shore', 'signature', 'Signature Piece', 1, '/shop.html', 'images/Silver_plumeria_1.png', '[{"url": "images/Silver_plumeria_2.png", "alt": "Silver Plumeria Drop Earrings — worn"}, {"url": "images/Silver_plumeria_1.png", "alt": "Silver Plumeria Drop Earrings — product"}]'::jsonb, true, false, 140, true),
  ('BP-STUDIO-002', 'Noir Pearl & Silver Statement Necklace', 85.00, 'pearl-crystal', 'signature', 'Studio Series', 1, '/shop.html', 'images/silver_black_1.png', '[{"url": "images/silver_black_2.png", "alt": "Noir Pearl & Silver Statement Necklace — worn"}, {"url": "images/silver_black_1.png", "alt": "Noir Pearl & Silver Statement Necklace — product"}]'::jsonb, true, false, 150, true),
  ('BP-STUDIO-003', 'Blue Ombré Crystal Necklace', 55.00, 'sea-shore', 'signature', 'Studio Series', 1, '/shop.html', 'images/blue_bracelet_1.png', '[{"url": "images/blue_bracelet_2.png", "alt": "Blue Ombré Crystal Necklace — worn"}, {"url": "images/blue_bracelet_1.png", "alt": "Blue Ombré Crystal Necklace — product"}]'::jsonb, true, false, 160, true),
  ('BP-STUDIO-004', 'Blue Sodalite & Pearl Necklace', 55.00, 'stone-earth', 'signature', 'Studio Series', 1, '/shop.html', 'images/blue_sodalite_1.png', '[{"url": "images/blue_sodalite_2.png", "alt": "Blue Sodalite & Pearl Necklace — worn"}, {"url": "images/blue_sodalite_1.png", "alt": "Blue Sodalite & Pearl Necklace — product"}]'::jsonb, true, false, 170, true),
  ('BP-STUDIO-005', 'Lava Stone & Gold Statement Necklace', 195.00, 'stone-earth', 'signature', 'Studio Series', 1, '/shop.html', 'images/LavaStone_1.png', '[{"url": "images/LavaStone_2.png", "alt": "Lava Stone & Gold Statement Necklace — worn"}, {"url": "images/LavaStone_1.png", "alt": "Lava Stone & Gold Statement Necklace — product"}]'::jsonb, true, false, 180, true),
  ('BP-STUDIO-006', 'Jade & Gold Chain Necklace', 50.00, 'stone-earth', 'signature', 'Studio Series', 1, '/shop.html', 'images/jade_1.png', '[{"url": "images/Jade_2.png", "alt": "Jade & Gold Chain Necklace — worn"}, {"url": "images/jade_1.png", "alt": "Jade & Gold Chain Necklace — product"}]'::jsonb, true, false, 190, true),
  ('BP-STUDIO-007', 'Honey & Frost Glass Necklace', 45.00, 'pearl-crystal', 'signature', 'Studio Series', 1, '/shop.html', 'images/yellow_white_1.png', '[{"url": "images/yellow_white_1.png", "alt": "Honey & Frost Glass Necklace — worn"}, {"url": "images/yellow_white_2.png", "alt": "Honey & Frost Glass Necklace — product"}]'::jsonb, true, false, 200, true),
  ('BP-N-014', 'Teal Aurora & Silver Sea-Charm Necklace', 55.00, 'sea-shore', 'everyday', 'Everyday', 1, '/shop.html', 'images/everyday/BP-N-014.jpg', '[{"url": "images/everyday/BP-N-014.jpg", "alt": "Teal Aurora & Silver Sea-Charm Necklace"}]'::jsonb, true, false, 210, true),
  ('BP-N-002', 'Peridot & Aqua Glass Necklace', 45.00, 'pearl-crystal', 'everyday', 'Everyday', 1, '/shop.html', 'images/everyday/BP-N-002.jpg', '[{"url": "images/everyday/BP-N-002.jpg", "alt": "Peridot & Aqua Glass Necklace"}]'::jsonb, true, false, 220, true)
on conflict (sku) do nothing;
