#!/usr/bin/env python3
"""
ONE-TIME migration helper (kept as the record of how the catalog was migrated).

Transforms the pre-images-model catalog into the new shape and emits BOTH:
  * catalog/products.json rewritten in the new shape (images -> [{url,alt}],
    plus aiNote / position / published), canonical key order; and
  * supabase/migrations/20260819120001_backfill_catalog_data.sql — per-SKU
    UPDATEs that put the live DB into the exact same state.

Deriving both from one function guarantees the file and the DB match, so the
first full-generate sync is a byte-identical no-op.

Rules (reproduce the current storefront output exactly):
  * everyday tier OR single image -> single-photo card; alt = name
  * >=2 images -> slider; alt = "name — worn" / "name — detail" (featured) or
    "name — product" (studio)
  * featured = a signature piece whose first image is under images/featured/
    -> aiNote = true (the "shown on an AI model" note + lazy-load)
  * position = array index * 10 + 10 (gaps of 10 so reordering never renumbers)
  * published = true for every current piece

Run once:  python catalog/_backfill_shape.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "catalog" / "products.json"
SQL = ROOT / "supabase" / "migrations" / "20260819120001_backfill_catalog_data.sql"

KEY_ORDER = ["sku", "name", "price", "collection", "tier", "label", "maxQuantity",
             "itemUrl", "cartImage", "images", "available", "aiNote", "position", "published"]


def transform(p, index):
    imgs = p.get("images") or []                    # old shape: list of path strings
    tier = p.get("tier") or "signature"
    featured = tier != "everyday" and bool(imgs) and imgs[0].startswith("images/featured/")
    single = tier == "everyday" or len(imgs) <= 1

    if single:
        new_images = [{"url": imgs[0], "alt": p["name"]}] if imgs else []
    else:
        second = "detail" if featured else "product"
        new_images = [
            {"url": imgs[0], "alt": f'{p["name"]} — worn'},
            {"url": imgs[1], "alt": f'{p["name"]} — {second}'},
        ]

    out = dict(p)
    out["images"] = new_images
    out["aiNote"] = featured
    out["position"] = index * 10 + 10
    out["published"] = True
    return {k: out[k] for k in KEY_ORDER if k in out}


def sqlstr(v):
    return "null" if v is None else "'" + str(v).replace("'", "''") + "'"


def main():
    doc = json.loads(DATA.read_text(encoding="utf-8"))
    doc["products"] = [transform(p, i) for i, p in enumerate(doc["products"])]
    DATA.write_bytes((json.dumps(doc, indent=2, ensure_ascii=False) + "\n").encode("utf-8"))

    lines = ["-- Generated by catalog/_backfill_shape.py — data backfill for the",
             "-- images-model migration. Apply AFTER 20260819120000 (schema).",
             "-- Puts every existing piece into the new shape so the first",
             "-- full-generate sync is a byte-identical no-op.\n"]
    for p in doc["products"]:
        imgs_json = json.dumps(p["images"], ensure_ascii=False).replace("'", "''")
        lines.append(
            f"update public.products set "
            f"images = '{imgs_json}'::jsonb, "
            f"ai_note = {str(p['aiNote']).lower()}, "
            f"position = {p['position']}, "
            f"published = true "
            f"where sku = {sqlstr(p['sku'])};")
    SQL.write_bytes(("\n".join(lines) + "\n").encode("utf-8"))
    print(f"Rewrote {DATA.relative_to(ROOT)} and wrote {SQL.relative_to(ROOT)} "
          f"({len(doc['products'])} pieces)")


if __name__ == "__main__":
    main()
